"""The published check reference, generated from the registry.

`registry.py` says the identifiers and the remediation strings are a published
interface. This module is what publishes them: it renders `CHECKS` into
`docs/contracts/doctor-checks.md`, which the contract-drift gate regenerates and
compares, so the document cannot describe a registry that no longer exists.

It lives here rather than in `reachy_contracts.contracts_export` because the
dependency runs this way — `reachy-checks` depends on `reachy-contracts` and
never the reverse, and a registry in the contracts package that imported this
one would close that loop. `scripts/export_contracts.py` is the driver that
holds both registries together and writes one index over the pair.

Nothing here decides where the output goes: `export` takes a directory, and the
`Contract` type it is registered as comes from the contracts package so that one
gate covers every generated artifact in the repository.
"""

from __future__ import annotations

from typing import Final

from reachy_checks.registry import CHECKS, Check
from reachy_contracts.contracts_export import Contract

__all__ = ["CONTRACTS", "DOCTOR_CHECKS_PATH", "anchor_for", "render_doctor_checks"]

# Where the reference is written, relative to `docs/contracts/`.
DOCTOR_CHECKS_PATH: Final = "doctor-checks.md"

_PREAMBLE: Final = """\
# The `doctor` checks

Generated by `just contracts` from `reachy_checks.CHECKS`. Do not edit this file
by hand: the contract-drift gate regenerates it and fails on any difference.

Every check `reachyctl doctor` runs and the provisioning verification role
performs is declared once, in that registry — reachyctl REQ-056. The identifiers
below are stable names: `doctor` prints one per row, `docs/ops/troubleshooting.md`
is keyed to them, and renaming one is a breaking change.

A check whose prerequisites were not supplied is **skipped**, not failed. The
"Needs" column is what has to be supplied for it to run at all.
"""

_TABLE_HEADER: Final = "| Check | What it asks | Needs |\n|---|---|---|"


def anchor_for(check: Check) -> str:
    """Give the fragment that addresses one check's section in this document.

    Markdown anchors are derived from the heading text, and this document's
    headings are the identifiers alone. A dot is dropped and a hyphen is kept,
    so `groundstation.round-trip` becomes `groundstationround-trip` — which is
    unguessable enough that anything linking here should ask rather than
    construct it.

    Args:
        check: The check to address.

    Returns:
        The fragment, without its leading `#`.
    """
    return check.identifier.replace(".", "")


def _requirements_of(check: Check) -> str:
    """Name what has to be supplied before a check can run.

    Args:
        check: The check to describe.

    Returns:
        The requirement names, comma separated, or a dash when a check needs
        nothing supplied.
    """
    if not check.requires:
        return "—"
    return ", ".join(f"`{requirement.value}`" for requirement in check.requires)


def _section_of(check: Check) -> str:
    """Render one check's own section.

    Args:
        check: The check to render.

    Returns:
        The section, ending in a blank line.
    """
    lines = [
        f"### {check.identifier}",
        "",
        f"{check.description}.",
        "",
        f"**Needs:** {_requirements_of(check)}",
        "",
        "**Remediation, as `doctor` prints it:**",
        "",
        f"> {check.remediation.explanation}",
        "",
    ]
    if check.remediation.command:
        lines += ["```", check.remediation.command, "```", ""]
    return "\n".join(lines)


def render_doctor_checks(checks: tuple[Check, ...] = CHECKS) -> str:
    """Render the whole reference.

    Args:
        checks: The registry to describe. Defaults to the real one.

    Returns:
        The full content of the generated document.
    """
    rows = "\n".join(
        f"| [`{check.identifier}`](#{anchor_for(check)}) | {check.description} "
        f"| {_requirements_of(check)} |"
        for check in checks
    )
    sections = "".join(f"\n{_section_of(check)}" for check in checks)
    return f"{_PREAMBLE}\n{_TABLE_HEADER}\n{rows}\n{sections}"


CONTRACTS: Final[tuple[Contract, ...]] = (
    Contract(
        path=DOCTOR_CHECKS_PATH,
        summary="every `doctor` check, its identifier and its remediation",
        render=render_doctor_checks,
    ),
)
