"""Regeneration of every published contract artifact under `docs/contracts/`.

The drift gate this feeds is simple: regenerate, then fail if the working tree
changed. That only works if regeneration is a real operation with a real output,
so this module is the registry the generators plug into rather than a
placeholder the gate skips over. `CONTRACTS` is empty today — the wire types
whose schemas belong here do not exist yet — and the index it renders records
exactly that, which is a fact worth committing: an empty registry that says so
is checkable, and a check that is only wired up later is not.

Registering a generator is the whole of the work left. Append a `Contract` with
the path it writes under `docs/contracts/` and a callable that renders its
content, and the gate covers it with no further change here or in the workflow.
"""

from __future__ import annotations

import sys
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Final

__all__ = ["CONTRACTS", "INDEX_PATH", "Contract", "export", "render_all"]

INDEX_PATH: Final = "index.md"


@dataclass(frozen=True, slots=True)
class Contract:
    """One generated artifact and the source that produces it.

    Attributes:
        path: Where the artifact is written, relative to the output directory.
        summary: One line describing what the artifact pins.
        render: Produces the artifact's full content.
    """

    path: str
    summary: str
    render: Callable[[], str]


# Empty until the wire types exist. Generators are appended here.
CONTRACTS: Final[tuple[Contract, ...]] = ()

_PREAMBLE: Final = """\
# Generated contracts

Every file in this directory is generated by `just contracts` from the type
declarations in `packages/reachy-contracts`. Do not edit one by hand: the
contract-drift gate regenerates them and fails on any difference, so a manual
edit is reverted by the next run at best and blocks a merge at worst.
"""


_EMPTY_REGISTRY: Final = """\
No contract artifacts are generated yet. The registry in
`reachy_contracts.contracts_export` is empty, and this file is what the drift
gate compares against until the first generator is registered.
"""


def _render_index(contracts: Sequence[Contract]) -> str:
    """Render the index that lists every generated artifact.

    Args:
        contracts: The registered contracts.

    Returns:
        The full content of the index file.
    """
    if not contracts:
        return f"{_PREAMBLE}\n{_EMPTY_REGISTRY}"
    rows = "\n".join(
        f"| [`{contract.path}`]({contract.path}) | {contract.summary} |"
        for contract in sorted(contracts, key=lambda contract: contract.path)
    )
    return f"{_PREAMBLE}\n| Artifact | What it pins |\n|---|---|\n{rows}\n"


def render_all(contracts: Sequence[Contract] = CONTRACTS) -> dict[str, str]:
    """Render every contract artifact and the index that lists them.

    Args:
        contracts: The registered contracts.

    Returns:
        A mapping of output path, relative to the output directory, to content.

    Raises:
        ValueError: If two contracts claim the same output path, which would
            make the generated tree depend on registration order.
    """
    rendered = {INDEX_PATH: _render_index(contracts)}
    for contract in contracts:
        if contract.path in rendered:
            message = f"two contracts claim the same path: {contract.path}"
            raise ValueError(message)
        rendered[contract.path] = contract.render()
    return rendered


def export(
    out_dir: Path,
    contracts: Sequence[Contract] = CONTRACTS,
) -> list[Path]:  # pragma: no cover - writes to the filesystem
    """Write every rendered artifact under an output directory.

    Args:
        out_dir: The directory to write into, created if it does not exist.
        contracts: The registered contracts.

    Returns:
        The paths written, in sorted order.
    """
    written: list[Path] = []
    for relative, content in sorted(render_all(contracts).items()):
        destination = out_dir / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")
        written.append(destination)
    return written


if __name__ == "__main__":  # pragma: no cover - module entry point
    export(Path(sys.argv[1] if len(sys.argv) > 1 else "docs/contracts"))
