"""Regeneration of every published contract artifact under `docs/contracts/`.

The drift gate this feeds is simple: regenerate, then fail if the working tree
changed. That only works if regeneration is a real operation with a real output,
so this module is the registry the generators plug into rather than a
placeholder the gate skips over.

`CONTRACTS` now holds one JSON Schema per robot link message type, derived from
the same declarations that validate those messages at run time. One declaration
producing both is the point: a schema written by hand beside a type is a second
statement of the contract, free to disagree with the first, and the drift gate
would have nothing to compare that disagreement against.

Registering a further generator is still the whole of the work. Append a
`Contract` with the path it writes under `docs/contracts/` and a callable that
renders its content, and the gate covers it with no further change here or in
the workflow.
"""

from __future__ import annotations

import json
import sys
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Final

from reachy_contracts.session import (
    FrameHeader,
    ResultEnvelope,
    SessionAgreement,
    SessionClose,
    SessionError,
    SessionOffer,
)
from reachy_contracts.values import FaceDetections, GestureDetections, WireModel

__all__ = ["CONTRACTS", "INDEX_PATH", "Contract", "export", "render_all"]

INDEX_PATH: Final = "index.md"


@dataclass(frozen=True, slots=True)
class Contract:
    """One generated artifact and the source that produces it.

    Attributes:
        path: Where the artifact is written, relative to the output directory.
        summary: One line describing what the artifact pins.
        render: Produces the artifact's full content.
    """

    path: str
    summary: str
    render: Callable[[], str]


# Where the robot link schemas are written, relative to `docs/contracts/`.
_SCHEMA_DIRECTORY: Final = "robot-link"

# Declared so a consumer reading a published schema knows which dialect's rules
# apply to it. pydantic emits 2020-12 shapes but does not stamp the document.
_DIALECT: Final = "https://json-schema.org/draft/2020-12/schema"


def _schema_of(model: type[WireModel]) -> Callable[[], str]:
    """Build a renderer for one message type's JSON Schema.

    The validation schema rather than the serialisation one. The two agree for
    every message type here except the session offer, where the serialisation
    schema drops the credential's minimum length and the fact that it is a
    secret — so publishing it would describe a contract laxer than the one this
    package enforces, and a second implementation written against it could emit
    a message this package refuses.

    Args:
        model: The message type to describe.

    Returns:
        A callable rendering that type's schema, keys sorted so the output
        depends on the declaration and not on dictionary ordering.
    """

    def render() -> str:
        document = {
            "$schema": _DIALECT,
            **model.model_json_schema(mode="validation"),
        }
        text = json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False)
        return f"{text}\n"

    return render


# One schema per message type. `face-result` and `gesture-result` are the same
# envelope carrying different payloads, which is what makes a new capability a
# new row here rather than a change to `ResultEnvelope`.
_MESSAGE_TYPES: Final[tuple[tuple[str, type[WireModel], str], ...]] = (
    (
        "session-offer",
        SessionOffer,
        "the client's credential and the capabilities it can speak",
    ),
    (
        "session-agreement",
        SessionAgreement,
        "the capabilities both sides settled on",
    ),
    (
        "frame-header",
        FrameHeader,
        "a frame's sequence number and its opaque capture token",
    ),
    (
        "face-result",
        ResultEnvelope[FaceDetections],
        "face detections answering one frame",
    ),
    (
        "gesture-result",
        ResultEnvelope[GestureDetections],
        "gesture detections answering one frame",
    ),
    (
        "session-error",
        SessionError,
        "a failure report, optionally naming the frame it concerns",
    ),
    (
        "session-close",
        SessionClose,
        "the last message on a session and why it ended",
    ),
)

CONTRACTS: Final[tuple[Contract, ...]] = tuple(
    Contract(
        path=f"{_SCHEMA_DIRECTORY}/{slug}.schema.json",
        summary=summary,
        render=_schema_of(model),
    )
    for slug, model, summary in _MESSAGE_TYPES
)

_PREAMBLE: Final = """\
# Generated contracts

Every file in this directory is generated by `just contracts` from the type
declarations in `packages/reachy-contracts`. Do not edit one by hand: the
contract-drift gate regenerates them and fails on any difference, so a manual
edit is reverted by the next run at best and blocks a merge at worst.
"""


_EMPTY_REGISTRY: Final = """\
No contract artifacts are registered. The registry in
`reachy_contracts.contracts_export` is empty, so this index is the only file the
drift gate has to compare against.
"""


def _render_index(contracts: Sequence[Contract]) -> str:
    """Render the index that lists every generated artifact.

    Args:
        contracts: The registered contracts.

    Returns:
        The full content of the index file.
    """
    if not contracts:
        return f"{_PREAMBLE}\n{_EMPTY_REGISTRY}"
    rows = "\n".join(
        f"| [`{contract.path}`]({contract.path}) | {contract.summary} |"
        for contract in sorted(contracts, key=lambda contract: contract.path)
    )
    return f"{_PREAMBLE}\n| Artifact | What it pins |\n|---|---|\n{rows}\n"


def render_all(contracts: Sequence[Contract] = CONTRACTS) -> dict[str, str]:
    """Render every contract artifact and the index that lists them.

    Args:
        contracts: The registered contracts.

    Returns:
        A mapping of output path, relative to the output directory, to content.

    Raises:
        ValueError: If two contracts claim the same output path, which would
            make the generated tree depend on registration order.
    """
    rendered = {INDEX_PATH: _render_index(contracts)}
    for contract in contracts:
        if contract.path in rendered:
            message = f"two contracts claim the same path: {contract.path}"
            raise ValueError(message)
        rendered[contract.path] = contract.render()
    return rendered


def export(
    out_dir: Path,
    contracts: Sequence[Contract] = CONTRACTS,
) -> list[Path]:  # pragma: no cover - writes to the filesystem
    """Write every rendered artifact under an output directory.

    Args:
        out_dir: The directory to write into, created if it does not exist.
        contracts: The registered contracts.

    Returns:
        The paths written, in sorted order.
    """
    written: list[Path] = []
    for relative, content in sorted(render_all(contracts).items()):
        destination = out_dir / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")
        written.append(destination)
    return written


if __name__ == "__main__":  # pragma: no cover - module entry point
    export(Path(sys.argv[1] if len(sys.argv) > 1 else "docs/contracts"))
